### ISSUE TITLE
Daily Owl Frog Rule

### ISSUE THREAD

**Issue by boyuhou** [boyuhou/excel-scanner#1]
1. If no big gap, follow daily owl / pocket trend. Use 1min RL30 as a direction and find KCArea to go with it. Likely anticipate entry before frog line and go in.

Also need to research if the frog number is long term frog or short term frog

**Comment by smartbing** [comment]
thought 1: If the gap or 1/2 mins bar shoot outside of Frogbox, I think it's not a very good sign for entry as the extreme move could reverse very quickly. On the other hand, if no big gap and we see RL10/30 closely follow same direction and break Frogbox, maybe it's a good entry signal.

**Comment by boyuhou** [comment]
Cool I will think through it

**Comment by smartbing** [comment]
thought 2: Another thought from what I see, I think we can basically skip/ignore the very tight HFB or R range tickers. I.E. HFB is less than 10 cents or so.

**Comment by smartbing** [comment]
![20170918-gild-owl-5](https://user-images.githubusercontent.com/24257217/31209613-24b2a7c6-a95a-11e7-8052-e65fb1362ed4.png)
This is a good case of my Thought #1, the first 3 bars we see extreme down move outside of FB, but we can only tell the RL30 not down later. Definitely to think of how to avoid these type of patterns/signals.

**Comment by smartbing** [comment]
![20170918-orcl-owl-4](https://user-images.githubusercontent.com/24257217/31209663-95acc8c6-a95a-11e7-95fa-0551f54f2b4e.png)
Another interesting case to add to thought 1, we see an RLCO within the early time Frogbox, where later we do see that price breaks down FB, could be a good NL trade if go short, but I would aruge we see more cases to see if avoiding these type of patterns (RLCO early within FB then break) helps to filter the not so good ones from the good ones.

**Comment by smartbing** [comment]
![20170921-xlv-owl-4](https://user-images.githubusercontent.com/24257217/31260704-a93b6320-aa1d-11e7-80a6-244c38207b23.png)
Thought #3, the price breaks out FB in later session, but look at the previous pocket down I think we need to be cautious about this type of late down breaks, as I would say the momentum are almost used up from the previous down trend.

**Comment by smartbing** [comment]
![20170921-abt-owl-4](https://user-images.githubusercontent.com/24257217/31260756-15ab731a-aa1e-11e7-900b-53a7de8381db.png)
Just another good example to support my thought 3.
