### ISSUE TITLE
Create spread indicator

### ISSUE THREAD

**Issue by boyuhou** [boyuhou/excel-scanner#4]
![image](https://user-images.githubusercontent.com/1228804/32866638-b7dde43c-ca36-11e7-9f5d-d1a72e612d78.png)

**Comment by boyuhou** [comment]
https://ninjatrader.com/support/helpGuides/nt8/en-us/?getcurrentask.htm
https://ninjatrader.com/support/helpGuides/nt8/en-us/?getcurrentbid.htm

**Comment by lkuo** [comment]
https://drive.google.com/open?id=19E4T5XPzLk9Nxe85K36SQbZiDWa0PK67

**Comment by boyuhou** [comment]
This is good. I also commited the newer version based on yours in NT8/indicator spread.cs. It uses rectangle fill and have value in it.
